### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by danieljamesross** [Piesaac/shopTillyouDrop#2]
Watch out for spelling. `index.html` not `indeks.html`

**Comment by Piesaac** [comment]
this is because i already had a file called index.html and i didn't want to confuse the computer or myself

**Comment by danieljamesross** [comment]
I see, fair enough, however on github there is only one file. I suggest you move the file you have locally into a different folder. You will make _many_ `index.html` files in your career. Best practice is to keep them in separate folders.
